version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - blue-app
      - green-app

  blue-app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: blue-app
    environment:
      - APP_ENV=development
      - DB_HOST=postgres-container
      - REDIS_HOST=redis-container
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  green-app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: green-app
    environment:
      - APP_ENV=development
      - DB_HOST=postgres-container
      - REDIS_HOST=redis-container
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:latest
    container_name: redis-container
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fit123
      POSTGRES_DB: fit-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
