services:
  app-blue:
    container_name: fit-blue
    image: ${DOCKER_USERNAME}/fit-be:latest
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - blue/.env
    environment:
      - APP_PORT=3000
      - REDIS_HOST=redis-blue
      - REDIS_PORT=6379
      - APP_ENV=production
      - ENV_FILE=.env.blue
    networks:
      - redis-network
      - postgres-network
    depends_on:
      - redis-blue
      - postgres-blue

  app-green:
    container_name: fit-green
    image: ${DOCKER_USERNAME}/fit-be:latest
    restart: unless-stopped
    ports:
      - '3001:3000'
    env_file:
      - green/.env
    environment:
      - APP_PORT=3001
      - REDIS_HOST=redis-green
      - REDIS_PORT=6379
      - APP_ENV=production
      - ENV_FILE=.env.green
    networks:
      - redis-network
      - postgres-network
    depends_on:
      - redis-green
      - postgres-green

  redis-blue:
    container_name: redis-blue
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - redis-network
    restart: unless-stopped

  redis-green:
    container_name: redis-green
    image: redis:latest
    ports:
      - '6380:6379'
    networks:
      - redis-network
    restart: unless-stopped

  postgres-blue:
    container_name: postgres-blue
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=fit
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}
    networks:
      - postgres-network
    restart: unless-stopped

  postgres-green:
    container_name: postgres-green
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=fit
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}
    networks:
      - postgres-network
    restart: unless-stopped

networks:
  redis-network:
    driver: bridge
  postgres-network:
    driver: bridge
