services:
  app:
    container_name: fit-green
    image: sunghan123/fit-be:latest
    restart: unless-stopped
    ports:
      - '3001:3001'
    env_file:
      - .env.green
    networks:
      - redis-network

networks:
  redis-network:
    external: true
